# Kitty custom keybindings
map ctrl+shift+e launch --location=vsplit
map ctrl+shift+o launch --location=hsplit
map ctrl+shift+x toggle_layout stack
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down
map ctrl+scroll_up change_font_size all +2.0
map ctrl+scroll_down change_font_size all -2.0
